// Writes src/build-info.js (git-ignored, excluded from the zip) with the current commit, branch and
// time, so the panel's version line shows which checkout is loaded while testing a branch.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');
const git = (...args) => execFileSync('git', ['rev-parse', ...args], { cwd: root, encoding: 'utf8' }).trim();
const commit = git('HEAD');
const branch = git('--abbrev-ref', 'HEAD'); // "HEAD" when detached
const time = new Date().toISOString();
const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const out = path.join(root, 'src', 'build-info.js');
fs.writeFileSync(out, `// Generated by \`npm run stamp\`; git-ignored and never packed.
export default { commit: ${q(commit)}, short: ${q(commit.slice(0, 7))}, branch: ${q(branch)}, time: ${q(time)} };
`);
console.log(`${path.relative(root, out)}: ${commit.slice(0, 7)} · ${branch} · ${time}`);
